// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguageApp.Dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708170040_AddLastViewToTranslationInfoRelation")]
    partial class AddLastViewToTranslationInfoRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FrequencyIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("bit");

                    b.Property<string>("Language1Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language2Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermMeaning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermTranslation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("TermTranslationAudio")
                        .HasColumnType("varbinary(max)");

                    b.PrimitiveCollection<string>("TermTranslationTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("TranslationLearningInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DictionaryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FirstLearnAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastViewAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SecondLearnAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ThirdLearnAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TranslationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TranslationId");

                    b.HasIndex("UserId");

                    b.ToTable("TranslationLearningInfoTable");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TranslationLearningInfo", b =>
                {
                    b.HasOne("Translation", "Translation")
                        .WithMany("TranslationLearningInfos")
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("TranslationLearningInfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Translation", b =>
                {
                    b.Navigation("TranslationLearningInfos");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("TranslationLearningInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
